### ISSUE TITLE
bsModal counteracting wit the ecsu.css modal theme

### ISSUE THREAD

**Issue by jasdumas** [jasdumas/shinyGEO#39]
### Creating a greyed out background over the entire page and the modal is not interactive

If you comment out the `theme = ecsu.css` the problem remedies. I'm looking into an alternative such as using the HTML function/tag and structuring the modal windows that way.

![screen shot 2015-09-20 at 12 01 30 pm](https://cloud.githubusercontent.com/assets/6685750/9981593/61e7522a-5f8f-11e5-8fbb-819fe3ff542c.jpeg)

**Comment by gdancik** [comment]
Okay, good. I noticed this a little while ago and I thought it was something that I did. That's weird that the theme would cause that. Since we only really need the theme for the navbar colors, you can probably remove a lot of the CSS which we don't use and hopefully that will fix the problem.

**Comment by jasdumas** [comment]
I'll try that!

**Comment by jasdumas** [comment]
the current version solves this problem albeit without the shading which will be added shortly
