### ISSUE TITLE
About and Directions page on initial start

### ISSUE THREAD

**Issue by jasdumas** [jasdumas/shinyGEO#44]
## Question: should we have a pop-up that informs the user of an overview of the application or a home landing page? 

Initially the user is restricted to the expression profiles page until they select a GSE number and it downloads, while this is a good method to keep the user on the correct path to "eventual" analysis, the first view of the application is devoid of direction and purpose. As the picture below dictates:

![screen shot 2015-10-03 at 11 45 09 am](https://cloud.githubusercontent.com/assets/6685750/10263672/79d6b076-69c4-11e5-8f3b-b7bfc14180bd.jpeg)

**Comment by gdancik** [comment]
I like this idea. I'll try to do this this week.
