### ISSUE TITLE
Manual Selection does not have original Find/replace..

### ISSUE THREAD

**Issue by jasdumas** [jasdumas/shinyGEO#55]
... for columns that are not detected. 

![screen shot 2015-10-28 at 10 44 20 pm](https://cloud.githubusercontent.com/assets/6685750/10808790/94cac95c-7dc5-11e5-8284-f001db007601.jpeg)

**Comment by jasdumas** [comment]
I'm going to add this back in now

**Comment by jasdumas** [comment]
Actually the code looks like night/day since I've last been **in** the repo and I think I need help implementing this back

Help @gdancik or @mgdlxd ?

**Comment by gdancik** [comment]
Sorry, but I didn't see this until just now, but don't worry about it for
the moment as the UI is completely changing. For now the button will go to
the clinical summary but we're going to let the user toggle between the
clinical summary and the full clinical data. This is not implemented yet
but hopefully will be soon.
